app/urls.py
from . import views
from django.urls import path

app_name = "app"

urlpatterns = [
    path('cart', views.cart, name="cart"),
    path('order_summary', views.OrderSummaryView.as_view(), name="order_summary"),
    path('', views.HomeView.as_view(), name="home"),
    path('home', views.home, name="home"),
    path('signup', views.signup, name="signup"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('details/<slug>/', views.ItemDetailView.as_view(), name="details"),
    path('add_to_cart/<slug>/', views.add_to_cart, name="add_to_cart"),
    path('remove_from_cart/<slug>/', views.remove_from_cart, name="remove_from_cart"),
    path('remove_item_from_cart/<slug>/', views.remove_single_item_from_cart, name="remove_single_item_from_cart"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('checkout/',include('app2.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from app2.models import BillingAddress, Payment

from django_countries.fields import CountryField


User = settings.AUTH_USER_MODEL

CATEGORY_CHOICES = {
    ('T', 'touch'),
    ('K', 'keypade'),
    ('B', 'both'),
}


LABEL_CHOICES = {
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
}


class Item(models.Model):
    title = models.CharField(max_length=255)
    price = models.FloatField()
    desc = models.TextField(max_length=2250)
    img = models.ImageField(upload_to='pics')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("app:details", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("app:add_to_cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("app:remove_from_cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity *self.item.price

    def get_final_price(self):
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    ordered = models.BooleanField(default=False)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    start_date = models.DateTimeField(auto_now_add=True,)
    ordered_date = models.DateTimeField()
    billing_address = models.ForeignKey(BillingAddress, null=True, blank=True, on_delete=models.SET_NULL)
    payment = models.ForeignKey(Payment, null=True, blank=True, on_delete=models.SET_NULL)


    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">
    <link
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
            crossorigin="anonymous"
    >

    <title>{% block title %}{% endblock %}</title>
</head>
<body class="bg_light">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="background: skyblue">
    <a class="navbar-brand" href="home">Welcome</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="home">Home <span class="sr-only">(current)</span></a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'app:order_summary' %}">Cart</a>
            <a class="nav-item nav-link" href="logout">logout</a>
            {% else %}
            <a class="nav-item nav-link" href="signup">signup</a>
            <a class="nav-item nav-link" href="login">login</a>
            {% endif %}
        </div>
    </div>
</nav>

{% if messages %}
<div class="alert alert-warning" role="alert">
  {% for message in messages %}
     <h5>
         {{message}}
     </h5>
     {% endfor %}
</div>

{% endif %}
{% block content %}
{% endblock %}

<script
     src="https://code.jquery.com/jquery-2.2.2.min.js"
     integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI="
     crossorigin="anonymous"></script>
 <script
     src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
     integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
     crossorigin="anonymous"></script>

</body>
</html>

templates/cart.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">

    <title>Cart</title>
</head>
<body class="bg_light">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="background: skyblue">
    <a class="navbar-brand" href="home">Welcome</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="home">Home </a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link active" href="{{ BASE_DIR }}/cart">Cart <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="logout">logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ BASE_DIR }}/signup">signup</a>
            <a class="nav-item nav-link" href="{{ BASE_DIR }}/login">login</a>
            {% endif %}
        </div>
    </div>
</nav>
<h1>Cart</h1>
</body>
</html>

templates/checkout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">
    <link
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
            crossorigin="anonymous"
    >

    <title>Details</title>
</head>
<body class="bg_light">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="background: skyblue">
    <a class="navbar-brand" href="home">Welcome</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'app:order_summary' %}">Cart</a>
            <a class="nav-item nav-link" href="/logout">logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ BASE_DIR }}/signup">signup</a>
            <a class="nav-item nav-link" href="{{ BASE_DIR }}/login">login</a>
            {% endif %}
        </div>
    </div>
</nav>
{% if messages %}
<div class="alert alert-warning" role="alert">
  {% for message in messages %}
     <h5>
         {{message}}
     </h5>
     {% endfor %}
</div>

{% endif %}

<div class="container">
    <div class="py-5 text-center">
        <b><h1>Checkout</h1></b>
      </div>
<div class="row">

        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>
          <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <span class="text-muted">Product</span>
              <span class="text-muted">Price</span>
            </li>
              {% for order_item in object.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <span class="text-muted">{{order_item.quantity}} x {{order_item.item.title}}</span>
              <span class="text-muted">₹{{order_item.item.price}}</span>
            </li>
              {% endfor %}
              <li class="list-group-item d-flex justify-content-between bg-light">

              <div class="text-success">
                <input type="text" class="form-control" placeholder="Promo code">
                  </div>

              <button type="submit" class="btn btn-secondary">Redeem</button>

            </li>
           <!-- <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>-->
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (INR)</span>
              <strong>₹{{object.get_total}}</strong>
            </li>
          </ul>
        </div>
        <div class="col-md-8 order-md-1">


          <h4 class="mb-3">Billing address</h4>
          <form class="needs-validation" method="post">
            {% csrf_token %}
            <div class="mb-3">
              <label>Address</label>
              {{ form.street_address }}
              <div class="invalid-feedback">
                Please enter your shipping address.
              </div>
            </div>

            <div class="mb-3">
              <label >Address 2 <span class="text-muted">(Optional)</span></label>
              {{ form.apartment_address }}
            </div>

            <div class="row">
              <div class="col-md-5 mb-3">
                <label>Country</label>
                {{ form.country }}
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>
              <div class="col-md-5 mb-3">

              </div>
              <div class="col-md-5 mb-3">
                <label>State</label>
                {{ form.state }}
              </div>
              <div class="col-md-3 mb-3">
                <label>Zip</label>
                {{ form.zip }}
                <div class="invalid-feedback">
                  Zip code required.
                </div>
              </div>
            </div>
            <hr class="mb-4">
            <div>
              {{ form.same_billing_address }}
              <label>Shipping address is the same as my billing address</label>
            </div>
            <div>
              {{ form.save_info }}
              <label>Save this information for next time</label>
            </div>
            <hr class="mb-4">

            <h4 class="mb-3">Payment</h4>

            <div class="d-block my-3">
              <div class="custom-control custom-radio">
                {{ form.payment_options }}
              </div>
            </div>
            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
          </form>
        </div>
</div></div>
</body>
</html>

templates/details.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">
    <link
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
            crossorigin="anonymous"
    >

    <title>Details</title>
</head>
<body class="bg_light">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="background: skyblue">
    <a class="navbar-brand" href="/">Welcome</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'app:order_summary' %}">Cart</a>
            <a class="nav-item nav-link" href="/logout">logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ BASE_DIR }}/signup">signup</a>
            <a class="nav-item nav-link" href="{{ BASE_DIR }}/login">login</a>
            {% endif %}
        </div>
    </div>
</nav>
{% if messages %}
<div class="alert alert-warning" role="alert">
  {% for message in messages %}
     <h5>
         {{message}}
     </h5>
     {% endfor %}
</div>

{% endif %}
<div class="container">
    <div class="card">
        <div class="container-fliud">
            <div class="wrapper row">
                <div class="preview col-md-6">

                    <div class="preview-pic tab-content">
                        <div class="tab-pane active" id="pic-1"><img src="{{ object.img.url }}"/></div>

                    </div>


                </div>

                <div class="details col-md-6">
                    <h3 class="product-title">{{object.name}}</h3>

                    <p class="product-description">{{object.desc}}</p>
                    <h4 class="price">current price: <span>₹{{object.price}}</span></h4>

                    <div class="action">
                        <a href="{{object.get_add_to_cart_url}}" class="btn btn-warning">add to cart</a>
                        <a href="/" class="btn btn-warning">Continue Shopping</a><!--<button class="add-to-cart btn btn-default" type="button">add to cart</button>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}
Home
{% endblock %}
{% block content %}
<div class="container">
<div class="row">
    {% for item in object_list %}
    <div class="col">
        <div class="card" style="width: 18rem;">
            <img src="{{ item.img.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title" >{{item.title}}</h5>
                <h6 class="card-title">₹{{item.price}} INR</h6>
                <p class="card-text">{{item.get_category_display}} || {{item.get_label_display}}</p>
                <p class="card-text">{{item.desc}}</p>
                <a href="{{ item.get_absolute_url }}" class="btn btn-primary">Buy now</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
    </div>
{% endblock %}

templates/login.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">

    <title>login</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="background: skyblue">
    <a class="navbar-brand" href="home">Welcome <h1>{{username}}</h1></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="home">Home </a>
            {% if user.is.authenticated %}
            <h3><a href="app2/logout">logout</a></h3>
            {% else %}
            <a class="nav-item nav-link" href="signup">signup </a>
            <a class="nav-item nav-link active " href="login">login <span class="sr-only">(current)</span></a>
            {% endif %}
        </div>
    </div>
</nav>


    <h1>Log in</h1>
     {% if messages %}
<div class="alert alert-warning" role="alert">
  {% for message in messages %}
     <h5>
         {{message}}
     </h5>
     {% endfor %}
</div>

{% endif %}
    <form action="login" method="post">
    {% csrf_token %}

    <div class="form-row">
        <div class="form-group col-md-6">
            <input class="form-control"  name="username"  type="text" placeholder="username">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <input type="password" class="form-control" id="inputPassword4" name="password" placeholder="password">
        </div>
    </div>
    <button class="btn btn-primary" type="submit">Log in</button>


</form>

templates/order_summary.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">

        <link
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
            crossorigin="anonymous"
    >


    <title>OrderSummary</title>
</head>
<body class="bg_light">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="background: skyblue">
    <a class="navbar-brand" href="home">Welcome</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="home">Home </a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link active" href="{% url 'app:order_summary' %}">Cart<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="logout">logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ BASE_DIR }}/signup">signup</a>
            <a class="nav-item nav-link" href="{{ BASE_DIR }}/login">login</a>
            {% endif %}
        </div>
    </div>
</nav>



{% if messages %}
<div class="alert alert-warning" role="alert">
  {% for message in messages %}
     <h5>
         {{message}}
     </h5>
     {% endfor %}
</div>

{% endif %}



<div class="container">
    <div class="card">
        <div class="container-fliud">
            <div class="wrapper row">

                <h2> &nbsp;&nbsp;&nbsp;Order summary</h2>

                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col"> </th>
                        <th scope="col">#</th>
                        <th scope="col">Product name</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price</th>
                        <th scope="col">Total Price</th>
                        <th scope="col"> </th>
                        <th scope="col"> </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <td></td>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{order_item.item.title}}</td>
                        <td>₹{{order_item.item.price}}</td>
                        <td>
                            <a href="{% url 'app:remove_single_item_from_cart' order_item.item.slug %}"><span class="glyphicon glyphicon-minus"></span></a>
                            {{order_item.quantity}}
                            <a href="{% url 'app:add_to_cart' order_item.item.slug %}"><span class="glyphicon glyphicon-plus"></span></a>
                        </td>
                        <td>₹{{order_item.get_total_item_price}}</td>
                        <td>
                            <a href="{% url 'app:remove_from_cart' order_item.item.slug %}">
                            <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        </td>
                        <td></td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="5"><center><b>TOTAL PRICE</b></center></td>
                        <td colspan="3"><b>₹{{object.get_total}}</b></td>
                    </tr>
                    <tr>
                        <td colspan="8" > </td>
                    </tr>
                    <tr>
                        <td colspan="4">
                            <a href="/" class="btn btn-warning">
                                <center><b> Continue Shopping </b></center>
                            </a>
                        </td>
                        <td colspan="4">
                            <a href="/checkout" class="btn btn-warning float-right">
                                <center><b> Checkout </b></center>
                            </a>
                        </td>
                    </tr>
                    </tbody>
                </table>



            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/signup.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">

    <title>sign up</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="background: skyblue">
    <a class="navbar-brand" href="home">Welcome <h1>{{username}}</h1></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="home">Home </a>
            {% if user.is.authenticated %}
            <h3><a href="logout">logout</a></h3>
            {% else %}
            <a class="nav-item nav-link active " href="signup">signup <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="login">login</a>
            {% endif %}
        </div>
    </div>
</nav>
<form action="signup" method="post">
    <h1>REGISTRATION FORM</h1>
    {% csrf_token %}

    <div class="form-row">
        <div class="form-group col-md-6">
            <input class="form-control" name="first_name" placeholder="First name" type="text">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <input class="form-control" name="last_name" placeholder="Last name" type="text">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <input class="form-control" name="username" placeholder="username" type="text">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <input class="form-control" id="inputEmail4" name="email" placeholder="example@abc.com" type="email">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <input type="password" class="form-control" id="inputPassword4" name="password" placeholder="password">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <input type="text" class="form-control"  name="cpassword" placeholder="confirm password">
        </div>
    </div>
    <button class="btn btn-primary" type="submit">Sign up</button>


</form>
 <div>
     {% for message in messages %}
     <h3>
         {{message}}
     </h3>
     {% endfor %}
 </div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

</body>
</html>